version: "3.8"

services:
  mysqldb:
    image: mysql:8.1.0
    restart: unless-stopped
    env_file: poolapp/.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_User=$MYSQLDB_USER
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: poolapp
    restart: unless-stopped
    env_file: poolapp/.env
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
    db: {}