version: "3.8"

services:
  app:
    container_name: frontend-poolapp
    image: frontend-poolapp
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
