package com.fantasticfour.poolapp.CustomResponse;

public enum SignUpValidationEnum {
    IS_VALID,
    IS_EMPTY,
    INVALID_CHARACTERS_OTHER_THAN_HYPHEN_OR_PERIOD,
    IS_LONGER_THAN_50_CHAR,
    AREA_CODE_INVALID,
    NON_SEQUENTIAL_PHONE_NUMBER_REQUIRED,
    PHONE_NUMBER_COMPOSED_OF_DUPLICATE_CHARACTERS,
    PHONE_NUMBER_MUST_BE_LENGTH_0F_10_CHARACTERS,
    PHONE_NUMBER_MUST_CONSIST_OF_ONLY_NUMBERS
}
